###################### BUILDER ######################
FROM julia:latest

SHELL ["/bin/bash", "-c"]

ARG lang="C"

ENV DEBIAN_FRONTEND noninter active
ENV TERM xterm
ENV DISPLAY host.docker.internal:0.0
ENV LANG ${lang}
ENV LANGUAGE ${lang}
ENV LC_ALL ${lang}
ENV TZ Asia/Tokyo
ENV JULIA_NUM_THREADS 4

WORKDIR /root

COPY pkginstall.jl /root/

RUN apt -y update && apt -y upgrade &&\
    julia pkginstall.jl figure &&\
    rm -rf pkginstall.jl

COPY make-plot.jl src/logger.jl src/config.jl /root/