services:
  julia-run-de-1-sphere:
    container_name: "julia-run-de-1-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 0; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 1; done; done; done"]
  julia-run-de-3-sphere:
    container_name: "julia-run-de-3-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 10; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 3; done; done; done"]
  julia-run-de-5-sphere:
    container_name: "julia-run-de-5-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 20; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 5; done; done; done"]
  julia-run-de-1-rosenbrock:
    container_name: "julia-run-de-1-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 0; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 1; done; done; done"]
  julia-run-de-3-rosenbrock:
    container_name: "julia-run-de-3-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 10; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 3; done; done; done"]
  julia-run-de-5-rosenbrock:
    container_name: "julia-run-de-5-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 20; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 5; done; done; done"]
  julia-run-de-1-rastrigin:
    container_name: "julia-run-de-1-rastrigin"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 0; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 1; done; done; done"]
  julia-run-de-3-rastrigin:
    container_name: "julia-run-de-3-rastrigin"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 10; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 3; done; done; done"]
  julia-run-de-5-rastrigin:
    container_name: "julia-run-de-5-rastrigin"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.run
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin
      - METHOD=de
      - D=10 50 100
      - LOOP=1
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G 
    command: ["sh", "-c", "sleep 20; for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do julia main.jl $$d de cvt $$f 5; done; done; done"]

networks:
  default:
    driver: bridge